config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :forecast do
    resources :days, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forecast/days_controller.rb
class Forecast::DaysController < ApplicationController
  before_action :set_city_name

  def index
    handle_api_errors do
      @days = WeatherService::Api.new(city_name: @city_name).sixteen_day_forecast
    end
  end

  def show
    handle_api_errors do
      @day_number = params[:id]
      @day = WeatherService::Api.new(city_name: @city_name).specific_day_breakdown(day_number: @day_number)
    end
  end

  private

  def handle_api_errors
    yield
  rescue RestClient::NotFound => e
    redirect_to root_path, alert: "City #{@city_name} not found"
  rescue SocketError, RestClient::Exception => e
    Rails.logger.error "Error contacting API: #{e.message}\n #{e.backtrace.join("\n ")}"
    redirect_to root_path, alert: 'Error contacting API'
  end

  def set_city_name
    redirect_to root_path, alert: 'Please enter a city' if params[:city_name].blank?

    @city_name = params[:city_name]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nice_date date
    date.strftime("%A, %-d %b")
  end
end

app/helpers/forecast/days_helper.rb
module Forecast::DaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/forecast/days/index.html.erb
<h2>16 Day Forecast For <%= @city_name %></h2>

<%= link_to '<<< Back', root_path %>

<% @days.each_with_index do |day, index| %>
    <div class="card">
      <div class="card-header">
        <%= nice_date day.date %>
        <%= image_tag "http://openweathermap.org/img/w/#{day.icon}.png" %>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Avg. Temp:  <%= day.avg_temp %> Deg Celcius</li>
        <li class="list-group-item">Outlook:  <%= day.weather %></li>
      </ul>
      <div class="card-body">
        <%= link_to 'More >>>', forecast_day_path(index + 1, city_name: @city_name) %>
      </div>
    </div>
<% end %>

app/views/forecast/days/show.html.erb
<h2>Weather For <%= @city_name %> </h2>
<h3><%= nice_date @day.date %></h3>

<%= link_to '<<< Back', url_for(:back) %>

<div class="card">
  <div class="card-header">
    <%= nice_date @day.date %>
    <%= image_tag "http://openweathermap.org/img/w/#{@day.icon}.png" %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Wind Speed: <%= @day.wind_speed %></li>
    <li class="list-group-item">Morning Temp: <%= @day.morning_temp %> Deg Celcius</li>
    <li class="list-group-item">Evening Temp: <%= @day.evening_temp %> Deg Celcius</li>
    <li class="list-group-item">Night Temp: <%= @day.night_temp %> Deg Celcius</li>
    <li class="list-group-item">Avg. Temp:  <%= @day.avg_temp %> Deg Celcius</li>
    <li class="list-group-item">Outlook:  <%= @day.weather %></li>
    <li class="list-group-item">Humidity:  <%= @day.humidity %></li>
    <li class="list-group-item">Pressure:  <%= @day.pressure %></li>
  </ul>
</div>

app/views/home/index.html.erb
<%= form_tag(forecast_days_path, method: :get, class: 'form-inline') do %>
    <div class="form-group">
      <%= label_tag :city_name, 'Please enter a city name to see the forecast:' %>
      <%= text_field_tag :city_name, nil, class: 'form-control mx-sm-3' %>
      <%= button_tag 'Go', type: :submit, value: nil, class: 'btn btn-outline-success mx-sm-3' %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <nav id='main_nav' class="navbar navbar-expand-lg navbar-light bg-light">
      <h1><%= link_to 'WeatherApp', root_path %></h1>
    </nav>

    <% flash.each do |key, value| %>
        <div class="alert alert-danger"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>